language: go

install: go get -v github.com/spf13/hugo

env:
  global:
    - GIT_NAME="Shafiq Alibhai"
    - GIT_EMAIL="email@shafiq.in"
    - GIT_USERNAME=$username
    - GIT_PASSWORD=$password

script:
  - git remote set-url origin https://$GIT_USERNAME:$GIT_PASSWORD@github.com/shafiqissani/uk.deployview.com.git
  - git config --global user.name "$GIT_NAME"
  - git config --global user.email "$GIT_EMAIL"
  - git clone https://$GIT_USERNAME:$GIT_PASSWORD@github.com/shafiqissani/uk.deployview.com.git gh-pages
  - cd gh-pages
  - git checkout master
  - cd ..
  - hugo
  - cd public
  - mv * ../gh-pages/
  - cd ..
  - cd gh-pages
  - git add -A .
  - git commit --allow-empty -m "Deployed by Travis"
  - git push -u origin master --force | grep done | true

